language: node_js
node_js:
  - "8"
install:
  - cd ..
  - git init
  - git remote add origin https://github.com/eigenmethod/mam.git
  - git pull origin master
  - npm install
script:
  - npm start mol/app/demo mol/app/hello mol/app/supplies mol/app/habhub mol/app/todomvc mol/perf/sierp mol/perf/uibench mol/perf/dbmon mol/app/bench mol/app/bench/list/mol mol/app/bench/list/tsx mol/app/bench/chart/rope/mol mol/app/bench/chart/bar/mol mol/app/taxon mol/app/taxon/demo mol/app/users mol/mem mol/app/quine mol/app/lamps mol/app/files/demo mol/app/questions mol/app/slides mol/app/calc
  - rm mol/.gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: mol
  on:
    branch: master
notifications:
  slack: mam-mol:Z7vokFhXaSrMlPXzq6L93bUj
